//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ScrambleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScrambleService.IScramble")]
    public interface IScramble {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScramble/ScrambledWord", ReplyAction="http://tempuri.org/IScramble/ScrambledWordResponse")]
        ScrambleWCFServiceLib.Word ScrambledWord();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScramble/ScrambledWord", ReplyAction="http://tempuri.org/IScramble/ScrambledWordResponse")]
        System.Threading.Tasks.Task<ScrambleWCFServiceLib.Word> ScrambledWordAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScramble/WasCorrect", ReplyAction="http://tempuri.org/IScramble/WasCorrectResponse")]
        bool WasCorrect(string scrambledVal, string userAnswer);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScramble/WasCorrect", ReplyAction="http://tempuri.org/IScramble/WasCorrectResponse")]
        System.Threading.Tasks.Task<bool> WasCorrectAsync(string scrambledVal, string userAnswer);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScrambleChannel : Client.ScrambleService.IScramble, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScrambleClient : System.ServiceModel.ClientBase<Client.ScrambleService.IScramble>, Client.ScrambleService.IScramble {
        
        public ScrambleClient() {
        }
        
        public ScrambleClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScrambleClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScrambleClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScrambleClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ScrambleWCFServiceLib.Word ScrambledWord() {
            return base.Channel.ScrambledWord();
        }
        
        public System.Threading.Tasks.Task<ScrambleWCFServiceLib.Word> ScrambledWordAsync() {
            return base.Channel.ScrambledWordAsync();
        }
        
        public bool WasCorrect(string scrambledVal, string userAnswer) {
            return base.Channel.WasCorrect(scrambledVal, userAnswer);
        }
        
        public System.Threading.Tasks.Task<bool> WasCorrectAsync(string scrambledVal, string userAnswer) {
            return base.Channel.WasCorrectAsync(scrambledVal, userAnswer);
        }
    }
}
